# Цель

В данном блокноте приводятся основные понятия языка программирования Python, которые мы будем использовать.

В данной среде есть два вида ячеек: ячейки с кодом и ячейки с разметкой. У ячеек с кодом слева расположена надпись **In [ ]**.

Ячейки с кодом можно запускать, выделив ее и нажав комбинации *Shift + Enter* или *Сtrl + Enter*. Для примера выполните код, который находится в следующей ячейке.

## Hello world
Напишите в следующей ячейке

print("Hello world!")


Функция print() выводит переданное ей значение. То, что находится в кавычках называется строка.

## Переменные

Переменной называется некое хранилище данных. Мы будем использовать переменные для хранения чисел и матриц. 
Имя переменой должно начинаться с буквы и может содержать символы нижнего подчеркивания и цифры.
Например, переменные могут быть следующими.

In [2]:
a = 5
b = 10.3
Two_words = a

Теперь переменная $a$ содержит число 5, в $b$ содержится переменная 10.3. 
А в переменной $Two\_words$ содержится то, что содержится в переменной $a$.

Что бы узнать что храниться в переменной можно использовать функцию print(). Помните, что операции выполняются последовательно сверху вниз. Поэтому в выводе сначала идет переменная $a$, затем $b$, ну а после $Two\_words$.

In [3]:
print(a)
print(b)
print(Two_words)

5
10.3
5


## Арифметические операции

Нам потребуются всего 5 арифметических операций: сложение, вычитание, умножение, деление и возведение в степень.
В следующей ячейке приводятся примеры использования всех операций. Следует заметить, что сначала совершается арифметическая операция, а потом результат передается в print()

In [4]:
print(10 + 5)  # Сложение
print(10 - 5)  # Вычитание
print(10 * 5)  # Умножение
print(10 / 5)  # Деление
print(10 ** 5) # Возведение в степень

15
5
50
2.0
100000


Те же операции будут работать и с переменными, если в них находятся числа.

In [5]:
first = 10
second = 5

print(first + second)  # Сложение
print(first - second)  # Вычитание
print(first * second)  # Умножение
print(first / second)  # Деление
print(first ** second) # Возведение в степень 

15
5
50
2.0
100000


Все результаты арифметических операций моно совмещать и сохранять в переменные.

In [6]:
a = 10
b = 2
c = a-4 / b+1
print(c)

9.0


Обратите внимание на порядок выполнения операций. 

Операции выполняются слева на право в приоритете: умножение/деление, сложение/вычитание. То есть, сначала происходит деление 4 на b, так как у деления приоритет выше чем у сложения. Затем проученный результат вычитается из $a$ и к нему прибавляется 1.

Порядок следования можно поменять с помощью скобок. То, что находится в скобках выполняется в первую очередь.

In [7]:
a = 10
b = 2
c = (a-4) / (b+1)
print(c)

2.0


Обратите внимание на следующий пример.

In [8]:
a = 10
print(a)

b = 2
a = a + b
print(a)

a = a + 10
print(a)

10
12
22


$a = a + b$ означает сначала получить значение $a$ приравнять его к $b$. То есть, сначала совершается операция справа от знака равно. А затем происходит приравнивание.

## Задания

* Создать переменные с именами $val1$ и $val2$ и приравнять их к 1 и 20 соответственно.

In [9]:
from tutorial import *

In [11]:
#********************************


#********************************     

check_var(globals())

Молодец!


* А теперь переменные $a$ и $b$ уже созданы. Реализуй формулу $c = \frac{10a - 3b}{2}$.

In [12]:
a = 10
b = 3

#********************************     


#********************************     
   

check_formula(globals())

c не равно 45.5


## Массивы и списки

В этой части мы изучим такой мощный инструмент как списки и массивы.

Массивом называется переменная, которая содержит несколько значений, к которым можно обращаться по индексу. 

![alt](img/arrays.JPG)

Массив создается очень просто.
Мы просто записываем числа в квадратных скобках через запятую.

In [21]:
X = [4, 5, 3, 4, 5, 2, 5, 5]

Мы можем обращаться к элементам массива с помощью квадратных скобок. Элементы в массиве нумеруются начиная с нуля. То есть,
X[0] равно 4. А X[1] равно 5.

In [16]:
print(X[0])
print(X[1])

4
5


Элементы массива можно не только можно читать, но и записывать информацию в них.

In [17]:
print(X)
X[0] = 10
X[4] = 15
print(X)

[4, 5, 3, 4, 5, 2, 5, 5]
[10, 5, 3, 4, 15, 2, 5, 5]


Что бы узнать размер массива нужно воспользоваться функцией $len()$.

In [18]:
print(len(X))

8


## Циклы

Циклы удобно использовать в работе с массивами.

Пример цикла находится внизу.  

In [19]:
for i in range(10): # range(N) создает дипозон чисел от 0 до N, не включая N. То есть, 0, 1, ... , N-2, N-1
    print(i)

0
1
2
3
4
5
6
7
8
9


Цикл можно прочитать в следующем виде:

**Для $переменной$ в массиве/диапазоне:**
    * Тело цикла. (не забудьте про отступ)
    
Циклы удобно использовать для работы с массивами.  


In [20]:
for i in range(len(X)): 
    print(X[i])

10
5
3
4
15
2
5
5


#### Пример, подсчет суммы элементов в массиве

In [22]:
s = 0
for i in range(len(X)): 
    s = s + X[i]
print(s)

49


# Задание

#### Посчитать результат перемножения всех элементов в массиве

На вход подается массив $A$. Его размер можно узнать с помощью $len(A)$. Результат сохраните в  $res$.

In [16]:
res = 1
A = [1, 2, 3, 4, 5]
#**************************************
res = 1
for i in range(len(A)):
    res = res * A[i]
print (res)
#**************************************
check_array(A, res)

120
Молодец!


## Функции

Функции это участок кода, который выполняет определенную задачу.

Функция начинается со слова $def$ (сокращение от define, определим). Все что выполняется в функции должно начинаться с отступа. 
затем (синим) идет название функции. И наконец в скобках находятся переменные, которые передаются в функцию.

Затем что-то происходит в функции и после всего мы возвращаем результат ключевым словом $return$.

In [22]:
def first_function(a, b):
    
    print("В переменной а записано " + str(a))
    print("В переменной b записано " + str(b))
    c = a + b
    return c

result = first_function(a=1, b=2)
print(result)
print()

var1 = 20
var2 = 10

result = first_function(a=var1, b=var2)
print(result)

В переменной а записано 1
В переменной b записано 2
3

В переменной а записано 20
В переменной b записано 10
30


Обратите внимание, что когда мы передаем значения в функцию, то значение переменных приравнивается к передающимся значениям. 

Все переменные созданные в функции невидимы снаружи.

In [23]:
var = 1

print(var)

def second_function():
    var = 100
    return 0

print(var)

1
1


В Python встроено несколько специальных функций. 

Например, $len()$ возвращает размер массива.

Еще нам понадобится функция $sum()$, которая возвращает сумму массива.

In [24]:
s = sum(X)
print(s)

33


In [25]:
# код ниже позволяет найти среднее значение массива

mean = sum(X) / len(X)
print(mean)

4.125


# Матрицы

Работа с матрицами не встроена на прямую в Python. Но для этого существует библиотека NumPy (Numeric Python). 

Для того, что бы работать с этим модулем необходимо его подключить. В следующей ячейке находится пример того, как подключить эту библиотеку.

In [26]:
import numpy as np

Пример создания матрице находится в следующей ячейке.

In [27]:
A = np.array([ [1, 2, 3], [4, 5, 6] ])
print(A)

[[1 2 3]
 [4 5 6]]


In [28]:
B = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 10, 12]])
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]


Таким образом создается матрицы.

\begin{equation*}
\mathbf{A} = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{pmatrix} 
\end{equation*}

\begin{equation*}	
\mathbf{B} = \begin{pmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
\end{pmatrix}
\end{equation*}

Для создания матрицы в функцию np.array() передается массив строк матриц (который также является массивом).

В данной работе вам не нужно будет создавать матрицы самим.

Для обращения к элементу $A_{i, j}$ нужно написать $A[i, j]$.

In [29]:
print(A[0, 0])
print(A[1, 2])

1
6


In [30]:
print(B[2,0])
print(B[1,3])

9
8


Также имеется возможность обратиться к строке и колонке по отдельности. 

Что бы обратиться к строке нужно написать номер строки (только его). Что бы обратиться к колонке нужно вместо номера строки написать ":". В следующей ячейки примеры обращения к 0-ой строке матрицы $A$ и к третей колонке матрицы $B$.

In [31]:
print(A[0])
print(B[:, 3])

[1 2 3]
[ 4  8 12]


# Работа с матрицами

Мы можем использовать все операции с матрицами что были раньше и даже больше.

In [31]:
A = np.array([10., 10., 10, 10])
B = np.array([0, 1, 2, 3.])
C = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
D = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]])

print(A)
print()

print(B)
print()

print(C)
print()

print(D)

[ 10.  10.  10.  10.]

[ 0.  1.  2.  3.]

[[0 1 2 3]
 [4 5 6 7]]

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


Таким образом у нас есть матрицы:

\begin{equation*}
\mathbf{A} = \begin{pmatrix}
10  \\
10  \\
10  \\
10  \\
\end{pmatrix} 
\end{equation*}

\begin{equation*}
\mathbf{B} = \begin{pmatrix}
0  \\
1  \\
2  \\
3  \\
\end{pmatrix} 
\end{equation*}

\begin{equation*}
\mathbf{C} = \begin{pmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
\end{pmatrix} 
\end{equation*}

\begin{equation*}
\mathbf{D} = \begin{pmatrix}
1 & 2 & 3 \\
1 & 2 & 3 \\
1 & 2 & 3 \\
1 & 2 & 3 \\
\end{pmatrix} 
\end{equation*}

Не обращайте внимание на то, что вектор строка визуализируется как строка - это сделано для удобства.

Если у нас есть вектор колонка (например, A или B), то для обращения к элементу 

$B_{1, 0}$ достаточно написать $B[1]$. Да и вообще, $B_{1, 0}$ тоже самое, что и $B_{1}$.


In [32]:
print(B[1])

1.0


## Примеры работы с матрицами

### Сложение матриц

\begin{equation*}
result = \mathbf{A} + \mathbf{B} = \begin{pmatrix}
A_0  \\
A_1 \\
A_2  \\
A_3  \\
\end{pmatrix} 
+
\begin{pmatrix}
B_0  \\
B_1  \\
B_2  \\
B_3  \\
\end{pmatrix} = 
\begin{pmatrix}
A_0 + B_0  \\
A_1 + B_1  \\
A_2 + B_2  \\
A_3 + B_3  \\
\end{pmatrix} 
\end{equation*}

In [33]:
# с помощью цикла
result = np.zeros_like(A)

for i in range(len(A)):
    result[i] = A[i] + B[i]

print(result)

[ 10.  11.  12.  13.]


In [34]:
# с помощью матричных операций
result = A + B
print(result)

[ 10.  11.  12.  13.]


### Сумма элементов в матрице


\begin{equation*}
result = B_0 + B_1 + B_2 + B_3  
\end{equation*}

In [35]:
# с помощью цикла
result = 0
for i in range(len(B)):
    result = result + B[i] 

print(result)

6.0


In [36]:
# с помощью матричных операций
result = sum(B)
print(result)

6.0


## Реализация формулы

$$result
= 5 + 10B =
\begin{pmatrix}
5 + 10B_0  \\
5 + 10B_1  \\
5 + 10B_2  \\
5 + 10B_3  \\
\end{pmatrix}$$

In [37]:
# с помощью цикла
result = np.zeros_like(B)

for i in range(len(B)):
    result[i] = 5 + 10*B[i]

print(result)

[  5.  15.  25.  35.]


In [38]:
# с помощью матричных операций
result = 5 + 10*B
print(result)

[  5.  15.  25.  35.]


## Реализация формулы

$$result
= e^{\frac{B}{100}} =
\begin{pmatrix}
e^{\frac{B_0}{100}} \\
e^{\frac{B_1}{100}} \\
e^{\frac{B_2}{100}} \\
e^{\frac{B_3}{100}} \\
\end{pmatrix}$$

In [39]:
# с помощью цикла
result = np.zeros_like(B)
for i in range(len(B)):
    result[i] = np.exp(B[i] / 100)
print(result)

[ 1.          1.01005017  1.02020134  1.03045453]


In [40]:
# с помощью матричных операций
result = np.exp(B / 100)
print(result)

[ 1.          1.01005017  1.02020134  1.03045453]


## Реализации формулы

$$result
= \begin{pmatrix}
(A_0  B_0)^2  \\
(A_1  B_1)^2  \\
(A_2  B_2)^2  \\
(A_3  B_3)^2  \\
\end{pmatrix}$$

In [41]:
# с помощью цикла
result = np.zeros_like(B)

for i in range(len(B)):
    result[i] = (A[i]*B[i])**2

print(result)

[   0.  100.  400.  900.]


** Внимание. Помните, что по умолчанию при умножении матриц в Python происходит почленное умножение, а не матричное произведение.**

In [42]:
# с помощью матричных операций
result = (A*B)**2
print(result)

[   0.  100.  400.  900.]


## Реализации формулы

$$result = (A_0  B_0)^2 + (A_1  B_1)^2 + (A_2  B_2)^2 + (A_3  B_3)^2$$

In [43]:
# с помощью цикла
result = 0

for i in range(len(B)):
    result = result + (A[i]*B[i])**2

print(result)

1400.0


In [44]:
# с помощью матричных операций
result = sum((A*B)**2)
print(result)

1400.0


## Матричное произведение

$$
C \cdot B =
\begin{pmatrix}
C_{0, 0} & C_{0, 1} & C_{0, 2} & C_{0, 3} \\
C_{1, 0} & C_{1, 1} & C_{1, 2} & C_{1, 3} \\
\end{pmatrix} \cdot 
\begin{pmatrix}
B_0  \\
B_1  \\
B_2  \\
B_3  \\
\end{pmatrix}= 
\begin{pmatrix}
C_{0, 0} \cdot B_0 + C_{0, 1} \cdot B_1 + C_{0, 2} \cdot B_2 + C_{0, 3} \cdot B_3 \\
C_{1, 0} \cdot B_0 + C_{1, 1} \cdot B_1 + C_{1, 2} \cdot B_2 + C_{1, 3} \cdot B_3 \\
\end{pmatrix} =
\begin{pmatrix}
0 + 1 + 4 + 9\\
0 + 5 + 12 + 21 \\
\end{pmatrix}=
\begin{pmatrix}
14\\
38 \\
\end{pmatrix}
$$


In [44]:
result = np.dot(C, B)
print(result)

[ 14.  38.]


## Реализации формулы

$$result = 
\begin{pmatrix}
A_0 B_0 D_{0,2} \\
A_1 B_1 D_{1, 2} \\ 
A_2 B_2 D_{2,2} \\ 
A_3 B_3 D_{3,2} \\
\end{pmatrix}
$$

То есть, это почленное умножение вектора $A$, вектора $B$ и второй колонки матрицы $D$

In [45]:
# с помощью цикла
result = np.zeros_like(A)

for i in range(len(A)):
    result[i] = A[i]*B[i]*D[i, 2]
print(result)

[  0.  30.  60.  90.]


In [46]:
# с помощью матричных операций
result = (A*B)*D[:, 2]
print(result)

[  0.  30.  60.  90.]


## Самый сложный пример

$$result = 
\begin{pmatrix}
A_0 B_0 D_{0,0} + A_1 B_1 D_{1, 0} + A_2 B_2 D_{2,0} + A_3 B_3 D_{3,0} \\
A_0 B_0 D_{0,1} + A_1 B_1 D_{1, 1} + A_2 B_2 D_{2,1} + A_3 B_3 D_{3,1} \\
A_0 B_0 D_{0,2} + A_1 B_1 D_{1, 2} + A_2 B_2 D_{2,2} + A_3 B_3 D_{3,2} \\
\end{pmatrix}
$$

Или это можно переписать так:

$$result = 
\begin{pmatrix}
\sum_{i=0}^3{A_i B_i D_{i,0}} \\
\sum_{i=0}^3{A_i B_i D_{i,1}} \\
\sum_{i=0}^3{A_i B_i D_{i,2}} \\
\end{pmatrix}
$$

In [47]:
# с помощью цикла
result = np.array([0, 0, 0])
for i in range(len(result)):
    for j in range(len(A)):
        result[i] = result[i] + A[j]*B[j]*D[j, i]
print(result)

[ 60 120 180]


# Задания

Мы будем использовать следующие матрицы.

\begin{equation*}
\mathbf{A} = \begin{pmatrix}
10  \\
10  \\
10  \\
10  \\
\end{pmatrix}\mathbf{  }
\mathbf{B} = \begin{pmatrix}
0  \\
1  \\
2  \\
3  \\
\end{pmatrix}\mathbf{  }
\mathbf{C} = \begin{pmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
\end{pmatrix}
\mathbf{D} = \begin{pmatrix}
1 & 2 & 3 \\
1 & 2 & 3 \\
1 & 2 & 3 \\
1 & 2 & 3 \\
\end{pmatrix} 
\end{equation*}

И некое число a.

In [48]:
A = np.array([10., 10., 10, 10])
B = np.array([0, 1, 2, 3.])
C = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
D = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(D.shape[1])

3


## 1. Реализовать формулу
  
   \begin{equation*}
    res = a B = 
    \begin{pmatrix}
    a B_0 \\
    a B_1 \\
    a B_2 \\
    a B_3 \\
    \end{pmatrix}
    \end{equation*}

In [12]:
import numpy as np
from tutorial import *
res = np.zeros_like(B)
a = 3
#**************************************
for i in range ()
#**************************************
task_1(B, a, res)

[ 0.  3.  6.  9.]
Молодец!


## 2. Реализовать формулу
  
   \begin{equation*}
    res = A - a B = 
    \begin{pmatrix}
    A_0 - a B_0 \\
    A_1 - a B_1 \\
    A_2 - a B_2 \\
    A_3 - a B_3 \\
    \end{pmatrix}
    \end{equation*}

In [45]:
res = np.zeros_like(B)
a = 3
#**************************************
for i in range(len(A)):
    res[i] = A[i] - a * B[i]
print(res)


#**************************************
task_2(A, B, a, res)

print(A.shape)

[ 10.   7.   4.   1.]
Молодец!
(4,)


## 3. Реализовать формулу
  
   \begin{equation*}
    res = (A - a B)^2 = 
    \begin{pmatrix}
    (A_0 - a B_0)^2 \\
    (A_1 - a B_1)^2 \\
    (A_2 - a B_2)^2 \\
    (A_3 - a B_3)^2 \\
    \end{pmatrix}
    \end{equation*}

In [10]:
res = np.zeros_like(B)
a = 3
#**************************************
for i in range(len(A)):
    res[i] = (A[i] - a * B[i])**2
print(res)


#**************************************
task_3(A, B, a, res)

[ 100.   49.   16.    1.]
Молодец!


## 4. Реализовать формулу
  
$$res = a B = (A_0 - a B_0)^2 + (A_1 - a B_1)^2 + (A_2 - a B_2)^2 + (A_3 - a B_3)^2$$

In [14]:
res = 0
a = 3
#**************************************
res = sum((A - a * B)**2)
print(res)

#**************************************
task_4(A, B, a, res) 

166.0
Молодец!
